name: Relocate
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  relocate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Move contents
        run: |
          if [ -d "shiranui" ]; then
            rsync -av --exclude='.github' shiranui/ .
            rm -rf shiranui
          fi
          rm -f .github/workflows/relocate.yml
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          if ! git diff --staged --quiet; then
            git commit -m "Relocate contents"
            git push
          fi
